### PR TITLE
Feat/account 회원가입 기능 완료

### PR DESCRIPTION
**Pull request by kim-sangah**
회원가입 기능 완료 

https://github.com/nahyunkeem/feed/issues/1

### CODE REVIEW

**Review by nahyunkeem — APPROVED** [review]
LGTM!

**Comment by 9zimin9** [comment]
LGTM !

**Comment by kim-sangah** [comment]
화면 캡처 2024-11-04 233253
CustomUser = get_user_model > CustomUser = get_user_model()

**Comment by kim-sangah** [comment]
화면 캡처 2024-11-04 233355
화면 캡처 2024-11-04 233415

from datetime import timezone > from django.utils import timezone
timezone.now()

**Pull request merged**
